// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in guide/ent/runtime.go

const (
	Version = "v0.10.2-0.20220607144817-fd955654a08f"           // Version of ent codegen.
	Sum     = "h1:E+F0A1UrLcHwoEtBl1KN+OP0bQxUu5VyPIiWlmPUe18=" // Sum of ent codegen.
)
