// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"guide/ent/article"
	"guide/ent/segment"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Segment is the model entity for the Segment schema.
type Segment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Number holds the value of the "number" field.
	Number float64 `json:"number,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SegmentQuery when eager-loading is set.
	Edges            SegmentEdges `json:"edges"`
	article_segments *int
}

// SegmentEdges holds the relations/edges for other nodes in the graph.
type SegmentEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Article `json:"owner,omitempty"`
	// Features holds the value of the features edge.
	Features []*Feature `json:"features,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SegmentEdges) OwnerOrErr() (*Article, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// The edge owner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: article.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// FeaturesOrErr returns the Features value or an error if the edge
// was not loaded in eager-loading.
func (e SegmentEdges) FeaturesOrErr() ([]*Feature, error) {
	if e.loadedTypes[1] {
		return e.Features, nil
	}
	return nil, &NotLoadedError{edge: "features"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Segment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case segment.FieldNumber:
			values[i] = new(sql.NullFloat64)
		case segment.FieldID:
			values[i] = new(sql.NullInt64)
		case segment.FieldText:
			values[i] = new(sql.NullString)
		case segment.ForeignKeys[0]: // article_segments
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Segment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Segment fields.
func (s *Segment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case segment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case segment.FieldNumber:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				s.Number = value.Float64
			}
		case segment.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				s.Text = value.String
			}
		case segment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field article_segments", value)
			} else if value.Valid {
				s.article_segments = new(int)
				*s.article_segments = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryOwner queries the "owner" edge of the Segment entity.
func (s *Segment) QueryOwner() *ArticleQuery {
	return (&SegmentClient{config: s.config}).QueryOwner(s)
}

// QueryFeatures queries the "features" edge of the Segment entity.
func (s *Segment) QueryFeatures() *FeatureQuery {
	return (&SegmentClient{config: s.config}).QueryFeatures(s)
}

// Update returns a builder for updating this Segment.
// Note that you need to call Segment.Unwrap() before calling this method if this Segment
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Segment) Update() *SegmentUpdateOne {
	return (&SegmentClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Segment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Segment) Unwrap() *Segment {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Segment is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Segment) String() string {
	var builder strings.Builder
	builder.WriteString("Segment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", s.Number))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(s.Text)
	builder.WriteByte(')')
	return builder.String()
}

// Segments is a parsable slice of Segment.
type Segments []*Segment

func (s Segments) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
