// Code generated by ent, DO NOT EDIT.

package parameter

const (
	// Label holds the string label denoting the parameter type in the database.
	Label = "parameter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeFeaturedProducts holds the string denoting the featured_products edge name in mutations.
	EdgeFeaturedProducts = "featured_products"
	// EdgeFeatures holds the string denoting the features edge name in mutations.
	EdgeFeatures = "features"
	// Table holds the table name of the parameter in the database.
	Table = "parameters"
	// FeaturedProductsTable is the table that holds the featured_products relation/edge. The primary key declared below.
	FeaturedProductsTable = "features"
	// FeaturedProductsInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	FeaturedProductsInverseTable = "products"
	// FeaturesTable is the table that holds the features relation/edge.
	FeaturesTable = "features"
	// FeaturesInverseTable is the table name for the Feature entity.
	// It exists in this package in order to avoid circular dependency with the "feature" package.
	FeaturesInverseTable = "features"
	// FeaturesColumn is the table column denoting the features relation/edge.
	FeaturesColumn = "parameter_id"
)

// Columns holds all SQL columns for parameter fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// FeaturedProductsPrimaryKey and FeaturedProductsColumn2 are the table columns denoting the
	// primary key for the featured_products relation (M2M).
	FeaturedProductsPrimaryKey = []string{"product_id", "parameter_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
)
