// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// Feature is the predicate function for feature builders.
type Feature func(*sql.Selector)

// Parameter is the predicate function for parameter builders.
type Parameter func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Segment is the predicate function for segment builders.
type Segment func(*sql.Selector)
